apiVersion: v1
kind: ConfigMap
metadata:
  name: terraformplan-{{ .Release.Name }}{{ .Release.Revision }}
data:
  consul-template.sh: |-
    #!/bin/sh

    apk add --no-cache jq

    SERVICE_ACCOUNT_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    export VAULT_ADDR={{ .Values.vault.url }}

    VAULT_TOKEN=$(curl -sb \
        --request POST \
        --data "{\"role\": \"infrapack\", \"jwt\": \"${SERVICE_ACCOUNT_TOKEN}\"}" \
        "${VAULT_ADDR}/v1/auth/kubernetes/login" | jq -r '.auth .client_token')

    echo $VAULT_TOKEN

    consul-template \
        --vault-token=$VAULT_TOKEN \
        --vault-addr=$VAULT_ADDR \
        --vault-renew-token=false \
        -template "credentials.ctmpl:credentials.tf" \
        -once