apiVersion: v1
kind: ConfigMap
metadata:
  name: savestate-{{ .Release.Name }}{{ .Release.Revision }}
data:
  savestate.sh: |-
    #!/bin/sh

    TFSTATE_PATH="terraform/terraform.tfstate"
    PACKERSHA="packer/input.sha1"

    if [ -f $TFSTATE_PATH ]
    then
    TFSTATE="$(base64 < $TFSTATE_PATH)"
    CHOMP=$(echo $TFSTATE|tr -d ' ')
    TFPATCH="$(echo "{\"data\":{\"terraform.tfstate\": \"$CHOMP\"}}")"
    echo "Patching tfstate"
    kubectl patch secret state-infrapack -p="$TFPATCH"
    else
    echo "Not patching tfstate"
    fi

    if [ -f $PACKERSHA ]
    then
    PSTATE="$(base64 < $PACKERSHA)"
    PCHOMP=$(echo $PSTATE|tr -d ' ')
    PPATCH="$(echo "{\"data\":{\"input.sha1\": \"$PCHOMP\"}}")"
    echo "Patching packer checksum"
    kubectl patch secret state-infrapack -p="$PPATCH"
    else
    echo "Not patching packer checksum"
    fi