apiVersion: v1
kind: ConfigMap
metadata:
  name: savestate-{{ .Release.Name }}
data:
  savestate.sh: |-
    TFSTATE="$(base64 < terraform/terraform.tfstate)"
    CHOMP=$(echo $TFSTATE|tr -d ' ')
    TFPATCH="$(echo "{\"data\":{\"terraform.tfstate\": \"$CHOMP\"}}")"
    kubectl patch secret state-infrapack -p="$TFPATCH"

    #Packer sha1
    PSTATE="$(base64 < packer/input.sha1)"
    PCHOMP=$(echo $PSTATE|tr -d ' ')
    PPATCH="$(echo "{\"data\":{\"input.sha1\": \"$PCHOMP\"}}")"
    kubectl patch secret state-infrapack -p="$PPATCH"