apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vault.fullname" . }}
spec:
  template:
    spec:
      serviceAccountName: {{ template "vault.fullname" . }}
      containers:
      - name: vaultconfig
        image: "{{ .Values.vault.image.repository }}:{{ .Values.vault.image.tag }}"
        workingDir: /config
        command: ["sh", "./config.sh"]
        volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ template "vault.fullname" . }}
      restartPolicy: Never
  backoffLimit: 4
